name: ICTV Configuration
type: module
description: 'A custom module that displays a form to manage the ICTV configuration settings'
package: ICTV
#configure: ictv_settings.form
core_version_requirement: ^8 || ^9
dependencies:
  - drupal:block
