
import { IBlastHit } from "./IBlastHit";


export interface ISequence {

   // The full path of the CSV file generated by BLAST.
   blast_csv: string;

   // The full path of the HTML file generated by BLAST.
   blast_html: string;

   // The (compressed) contents of the CSV file.
   csv_file?: string;

   // Errors returned by BLAST (I think)
   errors: string;

   // The BLAST hits
   hits: IBlastHit[];

   // The (compressed) contents of the HTML file.
   html_file?: string;

   // The name of the FASTA input file.
   //input_file: string;

   // The BLAST qseqid
   qseqid: string;

   // Were there hits?
   status: string;      
}