
import { IBlastHit } from "./IBlastHit";


export interface ISequence {

   // The full path of the CSV file generated by BLAST.
   blast_csv: string;

   // The full path of the HTML file generated by BLAST.
   blast_html: string;

   // Errors returned by BLAST (I think)
   errors: string;

   // The BLAST hits
   hits: IBlastHit[];

   // The BLAST qseqid
   qseqid: string;

   // Were there hits?
   status: string;      
}