
import { AlertBuilder } from "../../helpers/AlertBuilder";
import { AppSettings } from "../../global/AppSettings";
import { BlastHitsPanel } from "./panels/BlastHitsPanel";
import { Constants, GenerateUUID, Icon, PanelAction, PanelKey, ParameterKey, testJob } from "./Common";
import { ISequence } from "./ISequence";
import { ISeqSearchJob } from "./ISeqSearchJob";
import { ISeqSearchPanel } from "./panels/ISeqSearchPanel";
import { JobDetailsPanel } from "./panels/JobDetailsPanel";
import { WebStorageKey } from "../../global/Types";
import { SearchResultsPanel } from "./panels/SearchResultsPanel";
import { SequenceSearchService } from "../../services/SequenceSearchService";
//import tippy from "tippy.js";
import { UploadPanel } from "./UploadPanel";
import { Utils } from "../../helpers/Utils";


export class SequenceSearch {

   // The authentication token that will be used when making API calls.
   authToken: string;

   // The CSS selector for the container element where the Sequence Search UI will be rendered.
   containerSelector: string = null;

   // DOM elements
   elements: {
      blastHitsPanel: HTMLElement,
      container: HTMLElement,
      jobDetailsPanel: HTMLElement,
      searchResultsPanel: HTMLElement,
      uploadPanel: HTMLElement
   }

   job: ISeqSearchJob = null;

   panels: Map<PanelKey, ISeqSearchPanel>;

   //sequenceResults: Map<string, ISequence>;

   state: {

      // The current job UID (optional)
      jobUID: string,

      // The current result index (optional)
      resultIndex: number
   }

   // User information
   user: {
      email: string, 
      name: string,
      uid: string
   }

   
   // C-tor
   constructor(authToken_: string, containerSelector_: string, email_: string, 
      name_: string, userUID_: string) {
      
      // Validate parameters
      if (!authToken_ || authToken_.length < 1) { throw new Error("Invalid auth token in SequenceSearch"); }
      if (!containerSelector_ || containerSelector_.length < 1) { throw new Error("Invalid container selector in SequenceSearch"); }
      if (!email_ || email_.length < 1) { email_ = Constants.NO_EMAIL; }
      if (!name_ || name_.length < 1) { name_ = "Anonymous user"; }
      userUID_ = Utils.safeTrim(userUID_);


      this.authToken = authToken_;
      this.containerSelector = containerSelector_;

      this.user = {
         email: email_, 
         name: name_,
         uid: userUID_
      }

      this.elements = {
         blastHitsPanel: null,
         container: null,
         jobDetailsPanel: null,
         searchResultsPanel: null,
         uploadPanel: null
      }

      this.panels = new Map<PanelKey, ISeqSearchPanel>();

      this.state = {
         jobUID: null,
         resultIndex: NaN
      }
   }


   /*
   // Create a sequence result from a BLAST hit and a search result.
   createSequenceResult(blastHit_: IBlastHit, searchResult_: ISearchResult): ISequenceResult {

      return {

         // The full path of the CSV file generated by BLAST.
         blast_csv: searchResult_.blast_csv,

         // The full path of the HTML file generated by BLAST.
         blast_html: searchResult_.blast_html,

         // The (compressed) contents of the CSV file.
         csv_file?: searchResult_.csv_file,

         // Errors returned by BLAST (I think)
         errors: searchResult_.errors,

         // The BLAST hits
         hits: [blastHit_],

         // The (compressed) contents of the HTML file.
         html_file?: searchResult_.html_file,

         // The name of the FASTA input file.
         input_file: searchResult_.input_file,

         // The BLAST qseqid
         qseqid: blastHit_.qseqid,

         // Were there hits?
         status: searchResult_.status  
      }
   }*/

   // Create a SeqSearch URL using the current state. 
   createUrlUsingState(): string {
      
      let url = window.location.href;

      // Remove any existing query string parameters.
      let qIndex = url.indexOf("?");
      if (qIndex > -1) { url = url.substring(0, qIndex); }

      // Do we have a valid job UID?
      if (this.state.jobUID !== null && this.state.jobUID.length > 0) {
         url += `?${ParameterKey.job}=${this.state.jobUID}`;

         // Do we have a valid result index?
         if (this.state.resultIndex !== null && !isNaN(this.state.resultIndex)) { 
            url += `&${ParameterKey.result}=${this.state.resultIndex}`;
         }
      }
      
      return url;
   }

   /*async displayJob() {

      if (!this.job || !this.job.data || !this.job.data.results) {
         this.elements.blastContainer.innerHTML = "No results";
         return;
      }

      // Clear any existing content in the results container.
      this.elements.blastContainer.innerHTML = "";

      
      //----------------------------------------------------------------------------------------------------------------
      // Create the URL that can be used to view the job data.
      //----------------------------------------------------------------------------------------------------------------
      this.jobURL = window.location.href;

      // TODO: Get rid of this line soon!!!
      this.jobURL = this.jobURL.replace("test.ictv.global", "ictv.global");

      // Remove any existing query string parameters.
      let qIndex = this.jobURL.indexOf("?");
      if (qIndex > -1) { this.jobURL = this.jobURL.substring(0, qIndex); }

      this.jobURL += `?job=${this.job.uid}`;

      
      //----------------------------------------------------------------------------------------------------------------
      // Generate the HTML for the job results.
      //----------------------------------------------------------------------------------------------------------------
      let resultsHTML = "";

      let inputFiles = [];

      this.job.data.results.forEach((result_: ISearchResult, index_: number) => {

         // One-based instead of zero-based.
         const displayIndex = index_ + 1;

         // Get the result's taxon name.
         //let taxonName = result_.sseqid_lineage.species || "Unknown";

         let isFirstRank = true;
         let lineage = "";
         
         
         // Populate the lineage to be displayed.
         if (!result_.sseqid_lineage) {
            lineage = "No lineage";

         } else {

            // Iterate over the classification lineage ranks.
            Object.keys(result_.sseqid_lineage).forEach(rank_ => {

               // Skip the species rank.
               if (rank_ === "species") { return; } 

               // Lookup this rank's taxon name in the lineage.
               let name = Utils.safeTrim(result_.sseqid_lineage[rank_]);
               if (!name || name.length < 1) { return; }

               // Should we add a lineage delimiter?
               if (isFirstRank) { 
                  isFirstRank = false;
               } else {
                  lineage += this.icons.lineageDelimiter;
               }
   
               const formattedRank = LookupTaxonomyRank(rank_);

               lineage += `<span class="result-lineage">${formattedRank}: <i>${name}</i></span>`;
            })
         }
         
         // Add the input file to the list of files.
         if (!inputFiles.includes(result_.input_file)) { inputFiles.push(result_.input_file); }

         // Add the input sequence to the list of sequences.
         //if (!inputSequences.includes(result_.input_seq)) { inputSequences.push(result_.input_seq); }

         let subjectInfo = "";

         // Display the BLAST subject and its GenBank accession(s), if available.
         if (!!result_.sseqid_accession && !!result_.sseqid_species_name) {
            
            const genbankLink = Utils.createGenBankAccessionLink(result_.sseqid_accession);

            subjectInfo = `<label>Virus name</label>: ${result_.sseqid_virus_names} (${genbankLink})`;
         }

         // Link the taxon name to the taxon details/history page.
         const detailsURL = `https://${window.location.hostname}/${AppSettings.taxonHistoryPage}?taxon_name=${taxonName}`;
         const linkedName = `<a href="${detailsURL}" target="_blank">${taxonName}</a>`;

         let resultHTML =
            `<div class="sequence-result">
               <div class="info">
                  <div class="result-index">#${displayIndex}</div>
                  <div class="lineage-and-result">
                     <div class="lineage">${lineage}</div>
                     <div class="result">
                        <div class="result-name">
                           <span class="rank-name">Species</span>: 
                           <span class="taxon-name">${linkedName}</span>
                        </div>
                        <div class="data-row">${subjectInfo}</div>
                        <div class="data-row">
                           <label>Bitscore</label>: ${result_.bitscore} bits
                        </div>
                        <div class="data-row">
                           <label>E-value</label>: ${result_.evalue}
                        </div>
                     </div>
                  </div>
               </div>
               <div class="controls">
                  <button class="btn ${ButtonClass.viewHTML} has-tooltip" 
                     data-index="${index_}" 
                     data-tippy-content="Click to view the HTML results (${result_.blast_html})"
                  >${this.icons.html} View HTML results</button>
                  <button class="btn ${ButtonClass.downloadCSV} has-tooltip" 
                     data-index="${index_}"
                     data-tippy-content="Click to download the results as a CSV file (${result_.blast_csv})"
                  >${this.icons.csv} Download CSV results</button>
               </div>  
            </div>`; 

         //resultsHTML += resultHTML;
      })
   
      
      // Should the input file and input sequence labels be singular or plural?
      const filesS = inputFiles.length == 1 ? "" : "s";
      //const sequenceS = inputSequences.length == 1 ? "" : "s";

      // Convert the lists of files and sequences to delimited strings.
      const inputFilesHTML = inputFiles.join(", ");
      //const inputSequencesHTML = inputSequences.join(", ");

      let html = 
         `<hr />
         <div class="results">
            <div class="results-title">Your results</div>
            <div class="job-details">
               <div class="job-table">
                  <div class="job-row">
                     <label>Job name:</label>
                     <div class="job-value">${this.job.name || "(none)"}</div>
                  </div>
                  <div class="job-row">
                     <label>Job status:</label>
                     <div class="job-value">${this.job.status}</div>
                  </div>
                  <div class="job-row">
                     <label>Program and version:</label>
                     <div class="job-value">${this.job.data.program_name} (version ${this.job.data.version})</div>
                  </div>
                  <div class="job-row">
                     <label>Database:</label>
                     <div class="job-value">${this.job.data.database_title}</div>
                  </div>
                  <div class="job-row">
                     <label>Input file${filesS}:</label>
                     <div class="job-value">${inputFilesHTML}</div>
                  </div>
               </div>
               <div class="link-panel">
                  <div class="instructions">You can view these results again using the following URL:</div>
                  <div class="controls">
                     <a href="${this.jobURL}" target="_blank">${this.jobURL}</a> 
                     <button class="btn ${ButtonClass.copyURL}">${this.icons.copy} Copy to clipboard</button>
                  </div>
               </div>
            </div>
            <hr />
            <div class="blast-hits-title">BLAST Hits</div>
            <div class="sequence-results">${resultsHTML}</div>
         </div>`;

      this.elements.resultsContainer.innerHTML = html;

      // Get a reference to the results element.
      this.elements.results = this.elements.resultsContainer.querySelector(".results");
      if (!this.elements.results) { throw new Error("Invalid results element"); }

      // Add event handlers
      this.elements.results.addEventListener("click", async (event_) => this.handleResultsClick(event_));

      // Initialize tippy tooltips for the buttons
      tippy(".has-tooltip");
      
      return;
   }*/

   // Retrieve the job with this UID.
   async getJob() {

      if (!this.state.jobUID) {
         await AlertBuilder.displayError("No job UID provided");
         return; 
      }

      // Get the job data from the server.
      this.job = await SequenceSearchService.getSearchResults(this.authToken, this.state.jobUID, this.user.email, this.user.uid);

      // Populate sequence results from the job data.
      //this.populateSequenceResults();

      return;
   }

   /*
   populateSequenceResults() {

      this.sequenceResults = new Map<string, ISequenceResult>();

      this.job.data.results.forEach((searchResult_: ISearchResult) => {

         searchResult_.hits.forEach((hit_: IBlastHit) => {

            let sequenceResult: ISequenceResult = null;

            if (this.sequenceResults.has(hit_.qseqid)) { 
               sequenceResult = this.sequenceResults.get(hit_.qseqid);
               sequenceResult.hits.push(hit_);
               this.sequenceResults.set()
            } else {
               sequenceResult = this.createSequenceResult(hit_, searchResult_);
            }
         })
      })

   }*/

   // Handle the panel action that was provided.
   async handleAction(action_: PanelAction) {

      if (!action_) { throw new Error("Invalid action parameter"); }
      
      let loadBlastHits = false;
      let loadJobDetails = false;
      let loadSearchResults = false;
      let loadUpload = false;

      // All panels besides the upload panel need to load the job specified in the state.
      if (action_ != PanelAction.displayUpload && (!this.job || this.job.uid !== this.state.jobUID)) { await this.getJob(); }

      switch (action_) {

         case PanelAction.displayBlastHits:

            // Which panels will be loaded?
            loadBlastHits = true;
            loadJobDetails = true;
            loadUpload = true;
            break;

         case PanelAction.displayJob:

            // Reset the BLAST hit result index.
            this.state.resultIndex = NaN;

            // Which panels will be loaded?
            loadJobDetails = true;
            loadSearchResults = true;
            loadUpload = true;
            break;

         case PanelAction.displayUpload:

            // Clear the job and state.
            this.job = null;
            this.state.jobUID = null;
            this.state.resultIndex = NaN; 

            // Which panels will be loaded?
            loadUpload = true;

            break;

         default:
            return await AlertBuilder.displayError(`Unhandled panel action: ${action_}`);
      }

      // Load or unload panels as determined above.
      await this.updatePanel(PanelKey.blastHits, loadBlastHits);
      await this.updatePanel(PanelKey.jobDetails, loadJobDetails);
      await this.updatePanel(PanelKey.searchResults, loadSearchResults);
      await this.updatePanel(PanelKey.upload, loadUpload);

      return;
   }

   // Initialize the Sequence Search component.
   async initialize() {

      // If the user UID is empty, look for one in web storage or generate a new one.
      if (!this.user.uid) { this.setDefaultUserUID(); }

      // Get a reference to the container element.
      this.elements.container = <HTMLElement>document.querySelector(this.containerSelector);
      if (!this.elements.container) { throw new Error("Invalid container Element"); }

      // Create HTML for the container elements.
      const html = 
         `<div class=\"upload-panel container active\"></div>
         <div class=\"job-details-panel container\"></div>
         <div class=\"search-results-panel container\"></div>
         <div class=\"blast-hits-panel container\"></div>`;

      this.elements.container.innerHTML = html;

      // The BLAST hits panel
      this.elements.blastHitsPanel = this.elements.container.querySelector(".blast-hits-panel") as HTMLElement;
      if (!this.elements.blastHitsPanel) { throw new Error("Invalid BLAST hits panel Element"); }

      // The job details panel
      this.elements.jobDetailsPanel = this.elements.container.querySelector(".job-details-panel") as HTMLElement;
      if (!this.elements.jobDetailsPanel) { throw new Error("Invalid job details panel Element"); }

      // The search results panel
      this.elements.searchResultsPanel = this.elements.container.querySelector(".search-results-panel") as HTMLElement;
      if (!this.elements.searchResultsPanel) { throw new Error("Invalid search results panel Element"); }

      // The upload panel
      this.elements.uploadPanel = this.elements.container.querySelector(".upload-panel") as HTMLElement;
      if (!this.elements.uploadPanel) { throw new Error("Invalid upload panel Element"); }


      // Create the panel instances.
      this.panels.set(PanelKey.blastHits, new BlastHitsPanel(this.elements.blastHitsPanel, this));
      this.panels.set(PanelKey.jobDetails, new JobDetailsPanel(this.elements.jobDetailsPanel, this));
      this.panels.set(PanelKey.searchResults, new SearchResultsPanel(this.elements.searchResultsPanel, this));
      this.panels.set(PanelKey.upload, new UploadPanel(this.elements.uploadPanel, this));

      //--------------------------------------------------------------------------------------------------------------
      // Look for query string parameters and use them to determine which panel to display.
      //--------------------------------------------------------------------------------------------------------------

      // Set a default action.
      let action = PanelAction.displayUpload;

      // Was a job UID parameter provided?
      const urlParams = new URLSearchParams(window.location.search);
      
      // Was a job UID provided in the query string?
      this.state.jobUID = Utils.safeTrim(urlParams.get(ParameterKey.job));

      if (this.state.jobUID && this.state.jobUID.length > 0) {

         action = PanelAction.displayJob;

         this.state.resultIndex = NaN; 

         // Was a result index provided in the query string?
         let strResult = Utils.safeTrim(urlParams.get(ParameterKey.result));
         if (strResult) {
            this.state.resultIndex = parseInt(strResult, 10);

            // If a result index was provided, display the BLAST hits panel.
            if (!isNaN(this.state.resultIndex)) { action = PanelAction.displayBlastHits; }
         }
      }  

      return await this.handleAction(action);
   }

   // If the user UID is empty, look for one in web storage or generate a new one.
   async setDefaultUserUID() {

      // Is there already a user UID in web storage?
      if (typeof(Storage) !== "undefined") {
         this.user.uid = localStorage.getItem(WebStorageKey.sequenceSearchUserUID);

         console.log("userUID from web storage = ", this.user.uid)
      }

      if (!this.user.uid) { 

         // Generate a new user UID.
         this.user.uid = GenerateUUID(); 
      
         console.log("just generated this userUID: ", this.user.uid)

         if (typeof(Storage) !== "undefined") {

            // Save it in web storage
            localStorage.setItem(WebStorageKey.sequenceSearchUserUID, this.user.uid);
         }
      }

      return;
   }

   async updatePage() {

      const url = this.createUrlUsingState();
      window.location.assign(url);
      return;
   }

   // Unload/hide the specified panel.
   async updatePanel(panelKey_: PanelKey, load_: boolean) {

      // Get the requested panel.
      let panel: ISeqSearchPanel = this.panels.get(panelKey_);
      if (!panel) { throw new Error(`Unhandled panel: ${panelKey_}`); }

      if (load_) { 
         await panel.load(); 
      } else {
         await panel.unload();
      }

      return;
   }

}