
import { delegate, Props, ReferenceElement } from 'tippy.js';


// A callback function that uses an HTML element to generate HTML for the tooltip.
interface IGenerateHTML {
   (element_: ReferenceElement<Props>): string
}


// A class that builds a tooltip for elements that match a given DOM selector. When the user hovers over an 
// element that matches the selector, the tooltip will display HTML generated by a callback function.
export class TooltipBuilder {

   // The tooltip will be displayed on elements that have this DOM selector.
   elementSelector: string;

   /**
    * A callback function that generates HTML for the tooltip based on the referenced element.
    * @param element_ The element for which to generate tooltip HTML
    * @returns The generated HTML string
    */
   generateHTML: IGenerateHTML;


   // C-tor
   constructor(elementSelector_: string, callback_: IGenerateHTML) {

      if (!callback_) { throw new Error("Invalid HTML generator callback function parameter"); }
      this.generateHTML = callback_;

      if (!elementSelector_) { throw new Error("Invalid element selector parameter"); }
      this.elementSelector = elementSelector_;


      delegate(document.body, {

         allowHTML: true,

         // Provide any placeholder so the instance can show; we'll replace content in onShow
         content: " ",  // avoids "empty" tooltip edge cases

         //delay: [settings.tooltip.showDelay, settings.tooltip.hideDelay],

         // Does the tooltip contain clickable UI elements?
         interactive: true,

         target: this.elementSelector,
         
         // TODO: This should be a c-tor parameter that defaults to ICTV-Tooltip.
         theme: "ICTV-Tooltip",

         // Instance is the element that's hovered over.
         onShow: (instance_) => {
            const el = instance_.reference;
            instance_.setContent(this.generateHTML(el));
         }
      })
   }

   /**
    * Escapes HTML special characters in a string.
    * @param html_ The string to escape
    * @returns The escaped string
    */
   escapeHTML(html_: string) {
      return String(html_)
         .replace(/&/g, '&amp;')
         .replace(/</g, '&lt;')
         .replace(/>/g, '&gt;')
         .replace(/"/g, '&quot;')
         .replace(/'/g, '&#039;');
   }
}
