
DROP TABLE IF EXISTS `job`;

CREATE TABLE `job` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`created_on` DATETIME NULL DEFAULT current_timestamp(),
	`ended_on` DATETIME NULL DEFAULT NULL,
	`error_count` INT(10) UNSIGNED NULL DEFAULT '0',
	`error_message` TEXT NULL DEFAULT NULL,
	`info_count` INT(10) UNSIGNED NULL DEFAULT '0',
	`json` LONGTEXT NULL DEFAULT NULL,
	`message` TEXT NULL DEFAULT NULL,
	`name` VARCHAR(100) NULL DEFAULT NULL,
	`status_tid` INT(10) UNSIGNED NULL DEFAULT NULL,
	`success_count` INT(10) UNSIGNED NULL DEFAULT '0',
	`type_tid` INT(10) UNSIGNED NULL DEFAULT NULL,
	`uid` VARCHAR(100) NOT NULL,
	`user_email` TEXT NOT NULL,
	`user_uid` VARCHAR(100) NULL DEFAULT NULL,
	`warning_count` INT(10) UNSIGNED NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `FK_status_tid` (`status_tid`) USING BTREE,
	CONSTRAINT `FK_status_tid` FOREIGN KEY (`status_tid`) REFERENCES `ictv_apps`.`term` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
);
