ictv_virus_name_lookup_service.settings:
  type: config_object
  label: 'Settings for the ICTV Virus Name Lookup Service'
  mapping:
    databaseName:
      type: string
      label: 'The database name'
    drupalRoot:
      type: string
      label: 'The Drupal website root'