
CREATE TABLE IF NOT EXISTS `searchable_taxon` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The unique identifier of the taxon record',
  `division_tid` int(10) unsigned DEFAULT NULL COMMENT 'The NCBI Division ID (bacteria, mammals, viruses, etc.)',
  `filtered_name` varchar(1600) NOT NULL COMMENT 'The name with punctuation removed',
  `ictv_id` int(10) unsigned DEFAULT NULL,
  `ictv_taxnode_id` int(10) unsigned DEFAULT NULL COMMENT 'The corresponding taxnode_id in the ICTV database',
  `intermediate_name` varchar(300) DEFAULT NULL COMMENT 'A scientific name corresponding to a taxon name with a different name class. The scientific name is what will match an ICTV taxon.',
  `intermediate_rank` varchar(100) DEFAULT NULL COMMENT 'The taxonomic rank of the intermediate name',
  `is_valid` bit(1) NOT NULL DEFAULT b'1' COMMENT 'Is this taxon information current/valid or obsolete?',
  `name` varchar(1600) NOT NULL COMMENT 'The taxon name',
  `name_class_tid` int(10) unsigned NOT NULL COMMENT 'The category or type of name (ex. "scientific name"), inspired by NCBI name class',
  `parent_taxonomy_db_tid` int(10) unsigned DEFAULT NULL COMMENT 'The taxonomy database source of the taxon''s parent (optional)',
  `parent_taxonomy_id` int(11) unsigned DEFAULT NULL COMMENT 'The parent''s unique identifier within the parent taxonomy database',
  `rank_name_tid` int(10) unsigned DEFAULT NULL COMMENT 'The term ID of the taxonomic rank',
  `taxonomy_db_tid` int(10) unsigned NOT NULL COMMENT 'The taxonomy database source of this taxon''s information',
  `taxonomy_id` int(11) unsigned NOT NULL COMMENT 'The taxon''s unique identifier within the source taxonomy database',
  `version_id` int(10) DEFAULT NULL COMMENT 'For ICTV taxa, this corresponds to MSL release number',
  `created_on` datetime NOT NULL DEFAULT current_timestamp() COMMENT 'The date/time when this row was added to the database',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `FK_searchable_taxon_term` (`name_class_tid`) USING BTREE,
  KEY `FK_searchable_taxon_division` (`division_tid`) USING BTREE,
  KEY `FK_searchable_taxon_taxonomy_db` (`taxonomy_db_tid`) USING BTREE,
  KEY `FK_searchable_taxon_rank` (`rank_name_tid`) USING BTREE,
  KEY `idx_searchable_taxon_ictv_id` (`ictv_id`),
  FULLTEXT KEY `searchable_taxon_name_IDX` (`name`),
  CONSTRAINT `FK_searchable_taxon_division` FOREIGN KEY (`division_tid`) REFERENCES `term` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_searchable_taxon_rank_name` FOREIGN KEY (`rank_name_tid`) REFERENCES `term` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_searchable_taxon_taxonomy_db` FOREIGN KEY (`taxonomy_db_tid`) REFERENCES `term` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_searchable_taxon_term` FOREIGN KEY (`name_class_tid`) REFERENCES `term` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;