
CREATE TABLE `searchable_taxon` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'The unique identifier of the taxon record',
	`division_tid` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'The NCBI Division ID (bacteria, mammals, viruses, etc.)',
	`filtered_name` VARCHAR(500) NOT NULL COMMENT 'The name with punctuation removed' COLLATE 'utf8mb4_general_ci',
   `ictv_id` INT(11) UNSIGNED NOT NULL COMMENT 'The corresponding ictv_id from the ICTV database',
   `ictv_taxnode_id` INT(11) UNSIGNED NOT NULL COMMENT 'The corresponding taxnode_id from the ICTV database',
   `intermediate_name` VARCHAR(300) NULL COMMENT 'A scientific name corresponding to a taxon name with a different name class. The scientific name is what will match an ICTV taxon.',
	`intermediate_rank` VARCHAR(100) NULL COMMENT 'The taxonomic rank of the intermediate name',
   `is_valid` BIT(1) NOT NULL DEFAULT b'1' COMMENT 'Is this taxon information current/valid or obsolete?',
	`name` VARCHAR(500) NOT NULL COMMENT 'The taxon name' COLLATE 'utf8mb4_general_ci',
	`name_class_tid` INT(10) UNSIGNED NOT NULL COMMENT 'The category or type of name (ex. "scientific name"), inspired by NCBI name class',
	`parent_taxonomy_db_tid` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'The taxonomy database source of the taxon\'s parent (optional)',
	`parent_taxonomy_id` INT(11) UNSIGNED NULL DEFAULT NULL COMMENT 'The parent\'s unique identifier within the parent taxonomy database',
	`rank_name_tid` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'The term ID of the taxonomic rank',
	`taxonomy_db_tid` INT(10) UNSIGNED NOT NULL COMMENT 'The taxonomy database source of this taxon\'s information',
	`taxonomy_id` INT(11) UNSIGNED NOT NULL COMMENT 'The taxon\'s unique identifier within the source taxonomy database',
	`version_id` INT(10) NULL DEFAULT NULL COMMENT 'For ICTV taxa, this corresponds to MSL release number',
	`created_on` DATETIME NOT NULL DEFAULT current_timestamp() COMMENT 'The date/time when this row was added to the database',
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `FK_searchable_taxon_term` (`name_class_tid`) USING BTREE,
	INDEX `FK_searchable_taxon_division` (`division_tid`) USING BTREE,
	INDEX `FK_searchable_taxon_taxonomy_db` (`taxonomy_db_tid`) USING BTREE,
	INDEX `FK_searchable_taxon_rank` (`rank_name_tid`) USING BTREE,
	CONSTRAINT `FK_searchable_taxon_division` FOREIGN KEY (`division_tid`) REFERENCES `term` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_searchable_taxon_rank_name` FOREIGN KEY (`rank_name_tid`) REFERENCES `term` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_searchable_taxon_taxonomy_db` FOREIGN KEY (`taxonomy_db_tid`) REFERENCES `term` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_searchable_taxon_term` FOREIGN KEY (`name_class_tid`) REFERENCES `term` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)