ictv_sequence_classifier_service.settings:
  type: config_object
  label: 'Settings for the ICTV Sequence Classifier Service'
  mapping:
    csvResultsFilename:
      type: string
      label: 'The name of the CSV results file'
    databaseName:
      type: string
      label: 'The database name'
    drupalRoot:
      type: string
      label: 'The Drupal website root'
    htmlResultsFilename:
      type: string
      label: 'The name of the HTML results file'
    inputDirectory:
      type: string
      label: 'The directory where sequence files are uploaded'
    jobsPath:
      type: string
      label: 'The directory where job files are maintained'
    jsonResultsFilename:
      type: string
      label: 'The name of the JSON results file'
    outputDirectory:
      type: string
      label: 'The directory where output files are stored'
    scriptName:
      type: string
      label: 'The name of the sequence classifier script (from within a Docker container)'