ictv_sequence_classifier_service.settings:
  type: config_object
  label: 'Settings for the ICTV Sequence Classifier Service'
  mapping:
    databaseName:
      type: string
      label: 'The database name'
    drupalRoot:
      type: string
      label: 'The Drupal website root'
    jobsPath:
      type: string
      label: 'The directory where job files are maintained'