ictv_sequence_classifier_service.settings:
  type: config_object
  label: 'Settings for the ICTV Sequence Classifier Service'
  mapping:
    databaseName:
      type: string
      label: 'The database name'
    drupalRoot:
      type: string
      label: 'The Drupal website root'
    inputDirectory:
      type: string
      label: 'The directory where sequence files are uploaded'
    jobsPath:
      type: string
      label: 'The directory where job files are maintained'
    outputDirectory:
      type: string
      label: 'The directory where output files are stored'
    outputJsonFilename:
      type: string
      label: 'The name of the JSON output file'
    resultsFilename:
      type: string
      label: 'The name of the results file'
    scriptName:
      type: string
      label: 'The name of the sequence classifier script (from within a Docker container)'