ictv_id_page.settings:
  type: config_object
  label: 'Settings for the ICTV ID Page'
  mapping:
    databaseName:
      type: string
      label: 'The database name'
    drupalRoot:
      type: string
      label: 'The Drupal website root'
