ictv_taxablast_service.settings:
  type: config_object
  label: 'ICTV TaxaBLAST Service settings'
  mapping:
    databaseName:
      type: string
      label: 'The database name'
    dockerContainer:
      type: string
      label: 'The Docker container for the script'
    drupalRoot:
      type: string
      label: 'The Drupal website root'
    inputDirectory:
      type: string
      label: 'The directory where sequence files are uploaded'
    jobsPath:
      type: string
      label: 'The directory where job files are maintained'
    jsonResultsFilename:
      type: string
      label: 'The name of the JSON results file'
    maxTotalUploadSize:
      type: integer
      label: 'The maximum total size (in bytes) of all uploaded files'
    maxUploadedRecords:
      type: integer
      label: 'The maximum number of FASTA records/sequences that can be submitted (across all FASTA files that are uploaded)'
    outputDirectory:
      type: string
      label: 'The directory where output files are stored'
    scriptName:
      type: string
      label: 'The name of the TaxaBLAST script (in a Docker container)'
    scriptParameters:
      type: string
      label: 'Command line parameters for the TaxaBLAST script'