ictv_proposal_service.settings:
  type: config_object
  label: 'Settings for the ICTV Proposal Service'
  mapping:
    databaseName:
      type: string
      label: 'The database name'
    drupalRoot:
      type: string
      label: 'The Drupal website root'
    inputDirName:
      type: string
      label: 'The name of a proposal job input directory'
    jobsPath:
      type: string
      label: 'The directory where job files are maintained'
    outputDirName:
      type: string
      label: 'The name of a proposal job output directory'
    summaryFilename:
      type: string
      label: 'The name of the summary file generated for proposal job'